2024-11-13 04:53:06,987 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2024-11-13 06:13:45,253 - app - ERROR - Exception on /forgotPassword/password/Impvc2VtYXJpYTEuam1tcEBnbWFpbC5jb20i.ZzQ1dQ.3e6INDgkIl45EQggzIISuRb5_bw [GET]
Traceback (most recent call last):
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/core/decorators/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/routes.py", line 38, in resetPassword
    forgotPasswordService.checkToken(token)
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/services.py", line 90, in checkToken
    s = self.get_serializer()
        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ForgotpasswordService' object has no attribute 'get_serializer'. Did you mean: 'getSerializer'?
2024-11-13 06:13:45,258 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2024-11-13 06:16:36,200 - app - ERROR - Exception on /forgotPassword/password/Impvc2VtYXJpYTEuam1tcEBnbWFpbC5jb20i.ZzQ2KA.AZQnPQJJzxDOXnqh-fqhLYcfG-Y [GET]
Traceback (most recent call last):
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/core/decorators/decorators.py", line 14, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/app/modules/forgotPassword/routes.py", line 51, in resetPassword
    return render_template("forgot/forgotPasswordConfirmation.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josemorgado/Repo/RaboDeToro-hub-1/RaboDeToroHub1venv/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: forgot/forgotPasswordConfirmation.html
2024-11-13 06:16:36,202 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
